// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ljyswzvbssrhrxoewhwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxqeXN3enZic3NyaHJ4b2V3aHdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyODIwMjMsImV4cCI6MjA1Nzg1ODAyM30.PggqWBjxHpARAX3ieNZVFcxglBz6Ze7KkMWsqP9Vg8I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);